language: elixir
elixir: 1.9.0
notifications:
  recipients:
    - yevhenii@libraventur.es
otp_release:
  - 22.0.7
script:
  - "MIX_ENV=test mix do deps.get, test && mix compile && MIX_ENV=test mix coveralls.travis"
